#  참고 : https://www.binaryflavor.com/aws-s3-cloudfront-route53gwa-github-actionseuro-jeongjeog-webpeiji-baepo-hoseuting-jadonghwahagi/

name: Deploy to S3

on: [pull_request]   

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Cache node modules  
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-master-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: yarn 

      - name: Test
        run: yarn test
